SELECT k.YEAR, k.MONTH, k.GENDER, COUNT(DISTINCT k.USER_ID) AS USERS
FROM (SELECT EXTRACT(YEAR FROM a.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM a.SALES_DATE) AS MONTH,
    b.GENDER AS GENDER,
    a.USER_ID
    FROM ONLINE_SALE a JOIN USER_INFO b ON a.USER_ID = b.USER_ID
     ) k
WHERE k.GENDER IS NOT NULL
GROUP BY k.YEAR, k.MONTH, k.GENDER
ORDER BY k.YEAR, k.MONTH, k.GENDER;