-- 코드를 입력하세요
SELECT R.REST_ID,
I.REST_NAME,
I.FOOD_TYPE,
I.FAVORITES,
I.ADDRESS,
ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS R
JOIN REST_INFO AS I ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY R.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC